# Generated by Django 5.0.3 on 2024-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_image_image_image_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public_id',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
