# Generated by Django 5.0.3 on 2024-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_image_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='postphoto',
            name='image_url',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='postphoto',
            name='public_id',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
